// Saza: single-file Cloudflare Worker (generated by scripts/bundle.py, do not edit by hand)

// ===== utils.js =====
class ApiError extends Error {
  constructor(status, code, message) { super(message); this.status = status; this.code = code; }
}
const now = () => Math.floor(Date.now() / 1000);
const enc = new TextEncoder();

async function sha256(s) {
  const buf = await crypto.subtle.digest('SHA-256', enc.encode(s));
  return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('');
}
function randomHex(bytes) {
  return [...crypto.getRandomValues(new Uint8Array(bytes))].map(b => b.toString(16).padStart(2, '0')).join('');
}
function otpCode() {
  return String(10000 + (crypto.getRandomValues(new Uint32Array(1))[0] % 90000));
}
async function safeEqual(a, b) {
  const [x, y] = await Promise.all([sha256(String(a)), sha256(String(b))]);
  let d = 0;
  for (let i = 0; i < x.length; i++) d |= x.charCodeAt(i) ^ y.charCodeAt(i);
  return d === 0;
}
function normDigits(s) {
  return String(s ?? '')
    .replace(/[۰-۹]/g, d => '۰۱۲۳۴۵۶۷۸۹'.indexOf(d))
    .replace(/[٠-٩]/g, d => '٠١٢٣٤٥٦٧٨٩'.indexOf(d));
}

const BASE = {
  'Content-Type': 'application/json; charset=utf-8',
  'Cache-Control': 'no-store',
  'X-Content-Type-Options': 'nosniff',
};
function ok(data, status = 200, extra = {}) {
  return new Response(JSON.stringify({ success: true, data }), { status, headers: { ...BASE, ...extra } });
}
function fail(status, code, message, extra = {}) {
  return new Response(JSON.stringify({ success: false, error: { code, message } }), { status, headers: { ...BASE, ...extra } });
}

function getCookie(req, name) {
  const c = req.headers.get('Cookie') || '';
  const m = c.match(new RegExp('(?:^|; )' + name + '=([^;]*)'));
  return m ? m[1] : null;
}
function sessionCookie(value, maxAge) {
  return `sid=${value}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${maxAge}`;
}
function clientIp(req) {
  return req.headers.get('CF-Connecting-IP') || 'unknown';
}

async function readJson(req, max = 20000) {
  const len = Number(req.headers.get('content-length') || 0);
  if (len > max) throw new ApiError(413, 'PAYLOAD_TOO_LARGE', 'حجم درخواست زیاد است.');
  const text = await req.text();
  if (text.length > max) throw new ApiError(413, 'PAYLOAD_TOO_LARGE', 'حجم درخواست زیاد است.');
  try {
    const v = JSON.parse(text || '{}');
    if (v === null || typeof v !== 'object' || Array.isArray(v)) throw new Error('bad');
    return v;
  } catch {
    throw new ApiError(400, 'INVALID_JSON', 'درخواست نامعتبر است.');
  }
}

// Fixed-window rate limiter backed by D1. Returns true if the call is allowed.
async function hitRate(env, key, limit, windowSec) {
  const w = Math.floor(now() / windowSec) * windowSec;
  const row = await env.DB.prepare(
    'INSERT INTO rate_limits (key, window_start, count) VALUES (?, ?, 1) ' +
    'ON CONFLICT(key, window_start) DO UPDATE SET count = count + 1 RETURNING count'
  ).bind(key, w).first();
  if (Math.random() < 0.01) {
    await env.DB.prepare('DELETE FROM rate_limits WHERE window_start < ?').bind(now() - 86400).run();
  }
  return row.count <= limit;
}

// ===== config.js =====
// Central configuration. Change prices, credits and costs HERE only.

// Feature catalogue. `enabled: false` = not built yet; API answers 501 and the UI shows "coming soon".
const FEATURES = {
  chat:  { label: 'چت‌بات',         cost: 1,  maxInput: 2000, enabled: true  },
  image: { label: 'ساخت تصویر',     cost: 3,  maxInput: 500,  enabled: true  },
  video: { label: 'ساخت ویدئو',     cost: 10, maxInput: 500,  enabled: false },
  music: { label: 'ساخت موزیک',     cost: 5,  maxInput: 500,  enabled: false },
  edit:  { label: 'ویرایش هوشمند',  cost: 2,  maxInput: 500,  enabled: false },
};

// Paid plans (prices in Toman). Free plan credits come from env FREE_CREDITS.
const PAID_PLANS = {
  basic: { name: 'پایه',    price_toman: 99000,  credits: 150 },
  pro:   { name: 'حرفه‌ای', price_toman: 249000, credits: 500 },
};

function getPlans(env) {
  const free = Number.parseInt(env.FREE_CREDITS ?? '10', 10);
  return {
    free: { id: 'free', name: 'رایگان', price_toman: 0, credits: Number.isFinite(free) && free >= 0 ? free : 10 },
    ...Object.fromEntries(Object.entries(PAID_PLANS).map(([id, p]) => [id, { id, ...p }])),
  };
}

function limits(env) {
  const n = (v, d) => { const x = Number.parseInt(v ?? '', 10); return Number.isFinite(x) && x > 0 ? x : d; };
  return {
    aiPerMinute: n(env.RATE_AI_PER_MIN, 6),   // AI requests per user per minute
    otpPerIp: 10,                              // OTP sends per IP per 10 minutes
    otpPerPhone: 3,                            // OTP sends per phone per 10 minutes
    aiTimeoutMs: n(env.AI_TIMEOUT_MS, 60000),
    sessionDays: 30,
  };
}

// ===== sms.js =====
// SMS adapter (Kavenegar verify/lookup). Needs KAVENEGAR_KEY + OTP_TEMPLATE.
function smsConfigured(env) {
  return Boolean(env.KAVENEGAR_KEY && env.OTP_TEMPLATE);
}
async function sendOtpSms(env, phone, code) {
  const url = `https://api.kavenegar.com/v1/${env.KAVENEGAR_KEY}/verify/lookup.json` +
    `?receptor=${encodeURIComponent(phone)}&token=${encodeURIComponent(code)}&template=${encodeURIComponent(env.OTP_TEMPLATE)}`;
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), 15000);
  try {
    const r = await fetch(url, { signal: ctl.signal });
    return r.ok;
  } catch {
    return false;
  } finally {
    clearTimeout(t);
  }
}

// ===== ai.js =====
// AI provider layer. Frontend never sees keys; swap provider with AI_PROVIDER.
//   AI_PROVIDER=workers-ai (default)  -> Cloudflare Workers AI via the `AI` binding (no API key needed)
//   AI_PROVIDER=openai                -> any OpenAI-compatible API: AI_BASE_URL + AI_API_KEY
// Models: AI_TEXT_MODEL, AI_IMAGE_MODEL (defaults below).

const DEFAULT_TEXT_MODEL = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const DEFAULT_IMAGE_MODEL = '@cf/black-forest-labs/flux-1-schnell';
const NOT_CONFIGURED = () => new ApiError(503, 'AI_NOT_CONFIGURED', 'سرویس هوش مصنوعی هنوز راه‌اندازی نشده.');

function withTimeout(promise, ms) {
  let t;
  const timer = new Promise((_, rej) => { t = setTimeout(() => rej(new ApiError(504, 'AI_TIMEOUT', 'پاسخ از هوش مصنوعی دیر رسید. دوباره امتحان کن.')), ms); });
  return Promise.race([promise, timer]).finally(() => clearTimeout(t));
}

function mapProviderError(e) {
  if (e instanceof ApiError) return e;
  const status = e && (e.status || e.statusCode);
  const msg = String((e && e.message) || e || '');
  console.error('AI provider error:', status || '', msg.slice(0, 300));
  if (status === 429 || /rate.?limit|too many requests|capacity/i.test(msg)) {
    return new ApiError(429, 'AI_RATE_LIMIT', 'سرویس هوش مصنوعی الان شلوغه. چند لحظه بعد دوباره امتحان کن.');
  }
  if (/\b(401|403)\b|api.?key|unauthorized|permission|not authorized/i.test(msg) || status === 401 || status === 403) {
    return new ApiError(503, 'AI_NOT_CONFIGURED', 'سرویس هوش مصنوعی هنوز راه‌اندازی نشده.');
  }
  return new ApiError(502, 'AI_PROVIDER_ERROR', 'سرویس هوش مصنوعی در دسترس نیست. کمی بعد دوباره امتحان کن.');
}

function extractText(r) {
  if (typeof r === 'string') return r;
  if (!r || typeof r !== 'object') return '';
  if (typeof r.response === 'string') return r.response;
  if (r.result && typeof r.result.response === 'string') return r.result.response;
  const c = r.choices && r.choices[0] && r.choices[0].message && r.choices[0].message.content;
  if (typeof c === 'string') return c;
  if (typeof r.output_text === 'string') return r.output_text;
  return '';
}

function sniffMime(b64) {
  if (b64.startsWith('iVBOR')) return 'image/png';
  if (b64.startsWith('UklGR')) return 'image/webp';
  return 'image/jpeg';
}
function bytesToB64(buf) {
  const bytes = new Uint8Array(buf);
  let s = '';
  for (let i = 0; i < bytes.length; i += 0x8000) s += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  return btoa(s);
}

// ---------- providers ----------
async function openaiFetch(env, path, payload, ms) {
  if (!env.AI_API_KEY || !env.AI_BASE_URL) throw NOT_CONFIGURED();
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), ms);
  try {
    const r = await fetch(env.AI_BASE_URL.replace(/\/$/, '') + path, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${env.AI_API_KEY}` },
      body: JSON.stringify(payload),
      signal: ctl.signal,
    });
    if (!r.ok) { const err = new Error(`provider http ${r.status}`); err.status = r.status; throw err; }
    return await r.json();
  } catch (e) {
    if (e && e.name === 'AbortError') throw new ApiError(504, 'AI_TIMEOUT', 'پاسخ از هوش مصنوعی دیر رسید. دوباره امتحان کن.');
    throw e;
  } finally { clearTimeout(t); }
}

async function runText(env, messages, ms) {
  const provider = env.AI_PROVIDER || 'workers-ai';
  const model = env.AI_TEXT_MODEL || DEFAULT_TEXT_MODEL;
  let raw;
  if (provider === 'workers-ai') {
    if (!env.AI) throw NOT_CONFIGURED();
    raw = await withTimeout(env.AI.run(model, { messages, max_tokens: 1024 }), ms);
  } else if (provider === 'openai') {
    raw = await openaiFetch(env, '/chat/completions', { model: env.AI_TEXT_MODEL, messages, max_tokens: 1024 }, ms);
  } else {
    throw NOT_CONFIGURED();
  }
  const text = extractText(raw).trim();
  if (!text) throw new ApiError(502, 'AI_EMPTY_RESPONSE', 'هوش مصنوعی پاسخی نداد. دوباره امتحان کن.');
  return text;
}

async function runImage(env, prompt, ms) {
  const provider = env.AI_PROVIDER || 'workers-ai';
  let b64 = '';
  if (provider === 'workers-ai') {
    if (!env.AI) throw NOT_CONFIGURED();
    const raw = await withTimeout(env.AI.run(env.AI_IMAGE_MODEL || DEFAULT_IMAGE_MODEL, { prompt: prompt.slice(0, 2000) }), ms);
    if (raw && typeof raw.image === 'string') b64 = raw.image;
    else if (raw instanceof ReadableStream) b64 = bytesToB64(await new Response(raw).arrayBuffer());
    else if (raw instanceof ArrayBuffer || ArrayBuffer.isView(raw)) b64 = bytesToB64(raw.buffer || raw);
  } else if (provider === 'openai') {
    const raw = await openaiFetch(env, '/images/generations', {
      model: env.AI_IMAGE_MODEL, prompt: prompt.slice(0, 2000), n: 1, response_format: 'b64_json',
    }, ms);
    b64 = (raw && raw.data && raw.data[0] && raw.data[0].b64_json) || '';
  } else {
    throw NOT_CONFIGURED();
  }
  if (typeof b64 !== 'string' || b64.length < 200 || !/^[A-Za-z0-9+/=\s]+$/.test(b64)) {
    throw new ApiError(502, 'AI_INVALID_RESPONSE', 'خروجی نامعتبر از هوش مصنوعی گرفتیم. دوباره امتحان کن.');
  }
  return { base64: b64.replace(/\s/g, ''), mime: sniffMime(b64) };
}

// ---------- public API ----------
const CHAT_SYSTEM = 'You are a helpful assistant inside a Persian-language app. Reply in the same language as the user (default Persian), clearly and concisely.';

async function runChat(env, input, ms) {
  const text = await runText(env, [{ role: 'system', content: CHAT_SYSTEM }, { role: 'user', content: input }], ms);
  return { kind: 'text', text };
}

async function runImageGeneration(env, input, ms) {
  let prompt = input;
  if (/[\u0600-\u06FF]/.test(input)) {
    // Image models follow English best: translate/expand Persian ideas first. Falls back to the raw text if that step fails.
    try {
      prompt = (await runText(env, [
        { role: 'system', content: 'Turn the user idea into ONE detailed English image-generation prompt (max 60 words). Output only the prompt.' },
        { role: 'user', content: input },
      ], Math.min(ms, 20000))).slice(0, 1500);
    } catch { prompt = input; }
  }
  const img = await runImage(env, prompt, ms);
  return { kind: 'image', ...img, prompt };
}

// ===== auth.js =====

const PHONE_RE = /^09\d{9}$/;

function publicUser(u) {
  return { id: u.id, phone: u.phone, name: u.name || null, plan: u.plan, credits: u.credits, created_at: u.created_at };
}

// ---------- OTP: send ----------
async function sendOtp(req, env) {
  const body = await readJson(req);
  const phone = normDigits(body.phone).trim();
  if (!PHONE_RE.test(phone)) throw new ApiError(400, 'INVALID_PHONE', 'شماره موبایل معتبر نیست.');
  const L = limits(env);

  if (!(await hitRate(env, `otp-ip:${clientIp(req)}`, L.otpPerIp, 600))) {
    throw new ApiError(429, 'RATE_LIMITED', 'تعداد درخواست‌ها زیاد بود. چند دقیقه بعد دوباره امتحان کن.');
  }
  const recent = await env.DB.prepare('SELECT COUNT(*) AS c FROM otp_codes WHERE phone = ? AND created_at > ?')
    .bind(phone, now() - 600).first();
  if (recent.c >= L.otpPerPhone) {
    throw new ApiError(429, 'RATE_LIMITED', 'تعداد درخواست‌ها زیاد بود. چند دقیقه بعد دوباره امتحان کن.');
  }

  const sms = smsConfigured(env);
  const dev = env.DEV_MODE === '1';
  if (!sms && !dev) throw new ApiError(503, 'SMS_NOT_CONFIGURED', 'سرویس پیامک هنوز فعال نشده.');

  const code = otpCode();
  const hash = await sha256(`${code}:${phone}:${env.SESSION_SECRET || ''}`);
  await env.DB.prepare('INSERT INTO otp_codes (phone, code_hash, expires_at) VALUES (?, ?, ?)')
    .bind(phone, hash, now() + 120).run();

  if (sms) {
    const sent = await sendOtpSms(env, phone, code);
    if (!sent) throw new ApiError(502, 'SMS_FAILED', 'ارسال پیامک انجام نشد. کمی بعد دوباره امتحان کن.');
    return ok({ sent: true, expires_in: 120 });
  }
  // DEV_MODE only: returns the code in the response so you can test without an SMS account.
  return ok({ sent: true, expires_in: 120, dev_code: code });
}

// ---------- OTP: verify (register-or-login) ----------
async function verifyOtp(req, env) {
  const body = await readJson(req);
  const phone = normDigits(body.phone).trim();
  const code = normDigits(body.code).trim();
  if (!PHONE_RE.test(phone) || !/^\d{5}$/.test(code)) {
    throw new ApiError(400, 'INVALID_INPUT', 'اطلاعات واردشده معتبر نیست.');
  }
  const L = limits(env);

  const row = await env.DB.prepare(
    'SELECT id, code_hash, attempts FROM otp_codes WHERE phone = ? AND used = 0 AND expires_at > ? ORDER BY id DESC LIMIT 1'
  ).bind(phone, now()).first();
  if (!row) throw new ApiError(400, 'CODE_EXPIRED', 'کد منقضی شده. کد جدید بگیر.');
  if (row.attempts >= 5) throw new ApiError(429, 'TOO_MANY_ATTEMPTS', 'تعداد تلاش‌ها زیاد بود. کد جدید بگیر.');

  await env.DB.prepare('UPDATE otp_codes SET attempts = attempts + 1 WHERE id = ?').bind(row.id).run();
  const hash = await sha256(`${code}:${phone}:${env.SESSION_SECRET || ''}`);
  if (hash !== row.code_hash) throw new ApiError(400, 'WRONG_CODE', 'کد اشتباهه.');

  // consume the code atomically (a code can only be used once)
  const used = await env.DB.prepare('UPDATE otp_codes SET used = 1 WHERE id = ? AND used = 0').bind(row.id).run();
  if (used.meta.changes !== 1) throw new ApiError(400, 'CODE_EXPIRED', 'کد منقضی شده. کد جدید بگیر.');

  const free = getPlans(env).free.credits;
  const ts = now();
  const ins = await env.DB.prepare(
    "INSERT INTO users (phone, credits, plan, created_at, updated_at) VALUES (?, ?, 'free', ?, ?) ON CONFLICT(phone) DO NOTHING"
  ).bind(phone, free, ts, ts).run();
  const user = await env.DB.prepare('SELECT * FROM users WHERE phone = ?').bind(phone).first();
  const isNew = ins.meta.changes === 1;
  if (isNew && free > 0) {
    await env.DB.prepare('INSERT INTO credit_ledger (user_id, delta, reason) VALUES (?, ?, ?)')
      .bind(user.id, free, 'signup_bonus').run();
  }
  if (user.is_blocked) throw new ApiError(403, 'ACCOUNT_BLOCKED', 'این حساب مسدود شده است.');

  const token = randomHex(32);
  const maxAge = 60 * 60 * 24 * L.sessionDays;
  await env.DB.prepare('INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)')
    .bind(await sha256(token), user.id, ts + maxAge).run();

  return ok({ is_new: isNew, user: publicUser(user) }, 200, { 'Set-Cookie': sessionCookie(token, maxAge) });
}

// ---------- session helpers ----------
async function getUser(req, env) {
  const token = getCookie(req, 'sid');
  if (!token) return null;
  const u = await env.DB.prepare(
    'SELECT users.* FROM sessions JOIN users ON users.id = sessions.user_id WHERE sessions.token_hash = ? AND sessions.expires_at > ?'
  ).bind(await sha256(token), now()).first();
  return u || null;
}
async function requireUser(req, env) {
  const u = await getUser(req, env);
  if (!u) throw new ApiError(401, 'UNAUTHENTICATED', 'برای ادامه وارد شو.');
  if (u.is_blocked) throw new ApiError(403, 'ACCOUNT_BLOCKED', 'این حساب مسدود شده است.');
  return u;
}

async function logout(req, env) {
  const token = getCookie(req, 'sid');
  if (token) await env.DB.prepare('DELETE FROM sessions WHERE token_hash = ?').bind(await sha256(token)).run();
  return ok({ logged_out: true }, 200, { 'Set-Cookie': sessionCookie('', 0) });
}

async function updateProfile(req, env, user) {
  const body = await readJson(req);
  const name = String(body.name ?? '').replace(/[\u0000-\u001f<>]/g, '').trim();
  if (name.length < 1 || name.length > 40) throw new ApiError(400, 'INVALID_NAME', 'اسم باید بین ۱ تا ۴۰ حرف باشه.');
  await env.DB.prepare('UPDATE users SET name = ?, updated_at = ? WHERE id = ?').bind(name, now(), user.id).run();
  return ok({ user: publicUser({ ...user, name }) });
}

// ===== generate.js =====

// POST /api/ai/generate  { type, input }
async function generate(req, env, user) {
  const body = await readJson(req);
  const type = String(body.type ?? '');
  const input = String(body.input ?? '').replace(/\u0000/g, '').trim();
  const feat = Object.prototype.hasOwnProperty.call(FEATURES, type) ? FEATURES[type] : null;

  if (!feat) throw new ApiError(400, 'INVALID_TYPE', 'نوع درخواست معتبر نیست.');
  if (!feat.enabled) throw new ApiError(501, 'FEATURE_UNAVAILABLE', 'این ابزار هنوز آماده نشده و به‌زودی اضافه می‌شود.');
  if (!input) throw new ApiError(400, 'EMPTY_INPUT', 'اول توضیح چیزی که می‌خوای رو بنویس.');
  if (input.length > feat.maxInput) {
    throw new ApiError(400, 'INPUT_TOO_LONG', `متن حداکثر ${feat.maxInput} حرف می‌تونه باشه.`);
  }

  const L = limits(env);
  if (!(await hitRate(env, `ai:${user.id}`, L.aiPerMinute, 60))) {
    throw new ApiError(429, 'RATE_LIMITED', 'درخواست‌هات خیلی سریع بود. یه دقیقه صبر کن.');
  }

  // Reserve credits atomically BEFORE calling the provider (prevents overspending with parallel requests).
  const cost = feat.cost;
  const ts = now();
  const reserve = await env.DB.prepare(
    'UPDATE users SET credits = credits - ?, updated_at = ? WHERE id = ? AND credits >= ?'
  ).bind(cost, ts, user.id, cost).run();
  if (reserve.meta.changes !== 1) {
    throw new ApiError(402, 'INSUFFICIENT_CREDITS', 'اعتبار شما تمام شده است.');
  }

  const refund = async (code) => {
    await env.DB.batch([
      env.DB.prepare('UPDATE users SET credits = credits + ?, updated_at = ? WHERE id = ?').bind(cost, now(), user.id),
      env.DB.prepare('INSERT INTO credit_ledger (user_id, delta, reason) VALUES (?, ?, ?)').bind(user.id, cost, `refund:${type}`),
      env.DB.prepare('INSERT INTO ai_usage (user_id, request_type, credits_used, status, error_code) VALUES (?, ?, 0, ?, ?)')
        .bind(user.id, type, 'failed', code),
    ]);
  };

  let result;
  try {
    result = type === 'image'
      ? await runImageGeneration(env, input, L.aiTimeoutMs)
      : await runChat(env, input, L.aiTimeoutMs);
  } catch (e) {
    const err = mapProviderError(e);
    try { await refund(err.code); } catch (e2) { console.error('refund failed', e2 && e2.message); }
    throw err;
  }

  const id = randomHex(12);
  const fileId = result.kind === 'image' ? randomHex(16) : null;
  try {
    const stmts = [];
    if (fileId) {
      stmts.push(env.DB.prepare('INSERT INTO files (id, user_id, mime, data) VALUES (?, ?, ?, ?)').bind(fileId, user.id, result.mime, result.base64));
    }
    stmts.push(
      env.DB.prepare('INSERT INTO generations (id, user_id, type, input, output, file_id, credits_used) VALUES (?, ?, ?, ?, ?, ?, ?)')
        .bind(id, user.id, type, input, result.kind === 'text' ? result.text : null, fileId, cost),
      env.DB.prepare
